### ISSUE TITLE
Helpful Features

### ISSUE THREAD

**Issue by akbarbd** [meysamhadeli/booking-microservices-sample#21]
It's Awesome project.
 Thanks for making this repository.

I think  if you add more feature that would be helpful, like
1. Login , Authorization & Security.
2. Complex query 2 or All microservices.
3. Pagination.
4. Audit Log
5. SignalR 

 **@** if you have any plan to add UI then Add **React**
 
Thanks.
May Allah live long

**Comment by meysamhadeli** [comment]
Thanks, @akbarbd, for following my repository :)

1- For this we use `Identity server` and all endpoint must `authenticate` and `authorize` for security part.
2- I Don't have a plan for complex query o something like this. Most of my focus in `architecture level` and cover `technical part of microservices`.
3- I Don't Add plan for this, like section 2.
4- We have this right now in last version.
5- I Don't plan for it.
6- I Don't  have plan to add UI.

Thanks for feedback, Also I welcome to contribute that feature you mention :)
